DjangoProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from DjangoProject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.conf.urls import url
from django.urls import path
from account import views

app_name = "account"

urlpatterns = [
    path('', views.index, name='index'),
    path('show/<int:form_id>/', views.show, name='show'),
]

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp import views
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('success/', views.success, name='success'),
    path('main/', views.main, name='main'),
]

snsProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from snsProject import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('accounts/', include('accountapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models


class Data(models.Model):
    uid = models.CharField(max_length=30)
    passwd = models.CharField(max_length=30)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.uid


class Photo(models.Model):
    data = models.ForeignKey(Data, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)

accountapp/models.py
from django.db import models

# Create your models here.

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].disabled = True

account/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from account.models import Data, Photo


def index(request):
    if request.method == "POST":
        form = Data()
        form.uid = request.POST["uid"]
        form.passwd = request.POST["passwd"]
        form.pub_date = timezone.datetime.now()
        form.save()
        for img in request.FILES.getlist('image'):
            photo = Photo()
            photo.data = form
            photo.image = img
            photo.save()
        return redirect('show/' + str(form.id), form.id)
    else:
        return render(request, 'index.html')


def show(request, form_id):
    lst = get_object_or_404(Data, pk=form_id)
    return render(request, 'show.html', {'lst': lst})

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm

has_decorator = [login_required, account_ownership_required]

class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:success')
    template_name = 'create.html'


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'detail.html'


@method_decorator(has_decorator, 'get')
@method_decorator(has_decorator, 'post')
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:main')
    template_name = 'update.html'


@method_decorator(has_decorator, 'get')
@method_decorator(has_decorator, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'delete.html'


def success(request):
    return render(request, 'success.html')


@login_required
def main(request):
    return render(request, 'main.html')

account/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'index' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    아이디 : <input type="text" name="uid" > <br>
    비번 : <input type="password" name="passwd" > <br>
    사진 : <input type="file" name="image" multiple> <br>
    <input type="submit" value="전송"> <br>
    </a>
</form>
</body>
</html>

account/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% csrf_token %}
    {% if lst %}
    {% for x in lst.photo_set.all %}
        번호 : {{ x.data.id }} <br>
        아이디 : {{ x.data.uid }} <br>
        비번 : {{ x.data.passwd }} <br>
        사진 : <img src="{{ x.image.url }}" >
    <br>
    {% endfor %}
    {% endif %}
</body>
</html>

accountapp/templates/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{%  block contents %}
<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div>
        <h1>회원가입</h1>
    </div>
    <div>
        <form action="{% url 'accountapp:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="확인" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
</div>

{% endblock %}

accountapp/templates/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{%  block contents %}
<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div>
        <h6>회원 탈퇴를 원하시면 버튼을 누르세요</h6>
    </div>
    <div>
        <form action="{% url 'accountapp:delete' pk=user.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" value="탈퇴" class="btn btn-danger rounded-pill col-3 mt-3">
        </form>
    </div>
</div>

{% endblock %}

accountapp/templates/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{%  block contents %}
<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div>
        <h1>회원 정보</h1>
    </div>
    <div>
        <p>
            가입일 : {{ target_user.date_joined }}
        </p>
        <p>
            사용자명 : {{ target_user.username }}
        </p>
        {% if target_user == user %}
            <a href="{% url 'accountapp:update' pk=user.pk %}">
                <p>
                    회원 수정
                </p>
            </a>
            <a href="{% url 'accountapp:delete' pk=user.pk %}">
                <p>
                    회원 탈퇴
                </p>
            </a>
        {% endif %}

    </div>
</div>

{% endblock %}

accountapp/templates/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{%  block contents %}
<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div>
        <h1>로그인</h1>
    </div>
    <div class="mt-5">
        <form action="{% url 'accountapp:login' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="확인" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
</div>
{% endblock %}

accountapp/templates/main.html
{% extends 'base.html' %}

{%  block contents %}
<div style="text-align: center">
    <p></p>
    <h1> 메인 화면 </h1>
</div>
{% endblock %}

accountapp/templates/success.html
{% extends 'base.html' %}

{%  block contents %}
<div style="text-align: center">
    회원가입이 성공했습니다.
</div>
{% endblock %}

accountapp/templates/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{%  block contents %}
<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div>
        <h1>회원 수정</h1>
    </div>
    <div>
        <form action="{% url 'accountapp:update' pk=user.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="확인" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body>
{% include 'header.html' %}
<p></p><hr>

{% block contents %}

{% endblock %}

<p></p><hr>
{% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div style="text-align: center">
    <div>
        <span>공지사항</span>
        <span>제휴문의</span>
        <span>서비스 소개</span>
    </div>
        <div>
        <h6>Tstargram</h6>
    </div>
</div>

templates/head.html
<head>
    <meta charset="UTF-8">
    <title>Tstargram</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>

templates/header.html
<div style="text-align: center">
    <div>
        <h1>Tstargram</h1>
    </div>
    <div>
        <span>nav1</span>
        <span>nav2</span>
        <span>nav3</span>
        {% if not user.is_authenticated %}
        <a href="{% url 'accountapp:login' %}">
        <span>Login</span>
            <a href="{% url 'accountapp:create' %}">
                <span>Sign Up</span>
            </a>
        </a>
        {% else %}
        <a href="{% url 'accountapp:detail' pk=user.pk %}">
            <span>My Page</span>
        </a>
        <a href="{% url 'accountapp:logout' %}">
        <span>Logout</span>
        </a>
        {% endif %}
    </div>
</div>